Angular_15 upgrade
codedthemes/datta-able-free-angular-admin-template pull request #5
Opened 2022-11-28 09:54 UTC by ct-dixit

2022-11-29 06:42 UTC, phoenixcoded20 requested changes
Code has error as welll

2022-11-29 06:42 UTC, phoenixcoded20 commented on template/src/app/app.component.ts
>    ngOnInit() {
implements OnInit  is needed, without it ngOnInit() will not run, add back implements OnInit as well

2022-11-29 08:39 UTC, ct-dixit commented on template/src/app/app.component.ts
>    ngOnInit() {
done

2022-12-07 04:02 UTC, phoenixcoded20 approved these changes

2022-12-07 04:05 UTC, phoenixcoded20 approved these changes

2022-12-07 04:05 UTC, merged